server:
  port: 8081

spring:
  application:
    name: zuul-gateway


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8083/eureka/


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


zuul:
   prefix: /api
   routes:
     auth-service:
       path: /auth-service/**
       sensitiveHeaders:
#       url: http://localhost:8081
       serviceId : auth-service